apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.kasmApp.name | default "kasm" }}
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-guac
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{ .Values.kasmApp.name | default "kasm" }}-guac-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  kasmguac.app.config.yaml: |
    kasmguac:
      id: 00000000-0000-0000-0000-000000000000
      port: 3000
      cluster_size: CLUSTER_SIZE
      server_address: SERVER_ADDRESS
      server_port: SERVER_PORT
      zone: ZONE
      registration_token: REGISTRATION_TOKEN
      kasm_delete_session_watch_interval: 60
      recording:
        default_width: 1920
        default_height: 1080
        default_framerate: 12
        default_bitrate: 8
        retention_period_in_hours: 24
        encoding_queue_size: 2
        processing_interval: 30
        processing_cutoff: 30
        summary_interval: 300
        summary_include_intial_logs: true
      logging:
        errorEventName: error
        logDirectory: /opt/kasm/current/log/
        logRetentionDays: 7
        fileNamePattern: kasmguac-<DATE>.log
        dateFormat: YYYY.MM.DD
        timestampFormat: YYYY-MM-DD HH:mm:ss.SSS
    api:
      hostnames: ['APIHOSTNAME']
      port: 443
      auth_token: JWTTOKEN
      allow_self_signed_cert: true
      hostname_refresh_interval: 30
      public_jwt_cert: PUBLICCERT
      schema: https
